package dk.frankbille.iou.e2e

import com.p6spy.engine.logging.Category
import com.p6spy.engine.spy.P6SpyOptions
import com.p6spy.engine.spy.appender.FileLogger

class SeedDataCreator : FileLogger() {
    private var headerWritten = false

    override fun setLogfile(fileName: String?) {
        P6SpyOptions.getActiveInstance().append = false
        P6SpyOptions.getActiveInstance().databaseDialectDateFormat = "yyyy-MM-dd"
        P6SpyOptions.getActiveInstance().databaseDialectTimestampFormat = "yyyy-MM-dd HH:mm:ss"
        super.setLogfile("src/main/resources/db/changelog/changes/999-test-data.sql")
    }

    override fun logSQL(
        connectionId: Int,
        now: String?,
        elapsed: Long,
        category: Category?,
        prepared: String?,
        sql: String?,
        url: String?,
    ) {
        if (!headerWritten) {
            logText(
                """
                --liquibase formatted sql

                --changeset frankbille:999-test-data context:local

                # This file is auto-generated by TestDataIntegration using SeedDataCreator
                # To change the test data, edit the TestDataIntegration class and run the tests again

                """.trimIndent(),
            )
            headerWritten = true
        }

        if (sql?.lowercase()?.startsWith("select") == true) return

        val formattedSql = sql?.takeIf { it.isNotEmpty() }?.let { "$it;" } ?: ""

        super.logSQL(connectionId, now, elapsed, category, prepared, formattedSql, url)
    }
}
